[package]
exclude = [
	".drone",
	".git",
	".github",
	".gitignore",
	".scrutinizer.yml",
	".travis.yml",
	"krankerl.toml",
	"node_modules",
	"src"
]

before_cmds = [
	"npm install --deps",
	"npm run build",
]
